# Generated by Django 6.0 on 2025-12-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Home', 'Home'), ('Food', 'Food'), ('Transport', 'Transport'), ('Bills', 'Bills'), ('School', 'School'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Personal', 'Personal'), ('Savings', 'Savings'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Fuel', 'Fuel'), ('Rent', 'Rent'), ('Electricity Bill', 'Electricity Bill'), ('Internet', 'Internet'), ('Clothing', 'Clothing'), ('Medical', 'Medical'), ('Snacks & Drinks', 'Snacks & Drinks'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment')], max_length=100),
        ),
    ]
