# Generated by Django 6.0.4 on 2026-05-18 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_income'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Fuel', 'Fuel'), ('Rent', 'Rent'), ('Electricity Bill', 'Electricity Bill'), ('Internet', 'Internet'), ('Clothing', 'Clothing'), ('Medical', 'Medical'), ('Snacks & Drinks', 'Snacks & Drinks'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=100),
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=300, max_digits=12)),
                ('currency', models.CharField(choices=[('$', 'USD ($)'), ('R', 'ZAR (R)'), ('€', 'EUR (€)'), ('£', 'GBP (£)')], default='$', max_length=5)),
                ('low_balance_threshold', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
